version: '3.8'

services:

  mongodb:
    image: mongo:7.0
    container_name: mongodb-container
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: testdb

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: springboot-app
    restart: always

    depends_on:
      - mongodb

    ports:
      - "8082:8082"

    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017/testdb?authSource=admin

volumes:
  mongo_data: