spring.application.name=ReactiveDemo
#spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/BookManagement
#spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:admin123@mongodb:27017/testdb?authSource=admin}
server.port = 8082